### ISSUE TITLE
No need to remove superview

### ISSUE THREAD

**Issue by chaekit** [jerikjakobsen/Pathways#2]
You can also just hide the label by `.hidden = YES` there are different tradeoffs we can consider here

https://github.com/jerikjakobsen/Pathways/blob/38ce4a4a36b39bcc38288e194180dcaafb3398d5/Pathways/Views/Path/PathCell.m#L30

**Comment by jerikjakobsen** [comment]
I think leaving it as hidden may be better for most cases because when the cell is dequeued to be reused by the table view and tries to set the username label I think it would be removed and therefore not accessible. However for my case, a table view will only use cells that have the username label enabled or disabled and not mixed, so it should be ok. I still think it might be best practice to leave it as hidden just in case I decide to add a table view with mixed settings.

**Comment by chaekit** [comment]
yeah if adding/removing subview has some unnecessary minor performance penalty that often don't need to be paid by just using `hidden`
